// Footer.tsx
// Renders the footer region with site metadata. Kept minimal so themes and
// forks can extend it; the region is always present for stable styling.

import type { SiteIndex } from '../model.js';

export interface FooterProps {
  index: SiteIndex;
}

export function Footer(_props: FooterProps) {
  return <p>Generated by Typwiki.</p>;
}
